# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from remote_ros_mcp.proto.wrosbridge.v1 import action_pb2 as wrosbridge_dot_v1_dot_action__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in wrosbridge/v1/action_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ActionServiceStub:
    """ROS2 Action gRPC 서비스 정의
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendGoal = channel.unary_unary(
                '/wrosbridge.v1.ActionService/SendGoal',
                request_serializer=wrosbridge_dot_v1_dot_action__pb2.SendGoalRequest.SerializeToString,
                response_deserializer=wrosbridge_dot_v1_dot_action__pb2.SendGoalResponse.FromString,
                _registered_method=True)
        self.CancelGoal = channel.unary_unary(
                '/wrosbridge.v1.ActionService/CancelGoal',
                request_serializer=wrosbridge_dot_v1_dot_action__pb2.CancelGoalRequest.SerializeToString,
                response_deserializer=wrosbridge_dot_v1_dot_action__pb2.CancelGoalResponse.FromString,
                _registered_method=True)
        self.GetResult = channel.unary_unary(
                '/wrosbridge.v1.ActionService/GetResult',
                request_serializer=wrosbridge_dot_v1_dot_action__pb2.GetResultRequest.SerializeToString,
                response_deserializer=wrosbridge_dot_v1_dot_action__pb2.GetResultResponse.FromString,
                _registered_method=True)
        self.StreamFeedback = channel.unary_stream(
                '/wrosbridge.v1.ActionService/StreamFeedback',
                request_serializer=wrosbridge_dot_v1_dot_action__pb2.FeedbackStreamRequest.SerializeToString,
                response_deserializer=wrosbridge_dot_v1_dot_action__pb2.FeedbackStreamResponse.FromString,
                _registered_method=True)


class ActionServiceServicer:
    """ROS2 Action gRPC 서비스 정의
    """

    def SendGoal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelGoal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendGoal': grpc.unary_unary_rpc_method_handler(
                    servicer.SendGoal,
                    request_deserializer=wrosbridge_dot_v1_dot_action__pb2.SendGoalRequest.FromString,
                    response_serializer=wrosbridge_dot_v1_dot_action__pb2.SendGoalResponse.SerializeToString,
            ),
            'CancelGoal': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelGoal,
                    request_deserializer=wrosbridge_dot_v1_dot_action__pb2.CancelGoalRequest.FromString,
                    response_serializer=wrosbridge_dot_v1_dot_action__pb2.CancelGoalResponse.SerializeToString,
            ),
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=wrosbridge_dot_v1_dot_action__pb2.GetResultRequest.FromString,
                    response_serializer=wrosbridge_dot_v1_dot_action__pb2.GetResultResponse.SerializeToString,
            ),
            'StreamFeedback': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFeedback,
                    request_deserializer=wrosbridge_dot_v1_dot_action__pb2.FeedbackStreamRequest.FromString,
                    response_serializer=wrosbridge_dot_v1_dot_action__pb2.FeedbackStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wrosbridge.v1.ActionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wrosbridge.v1.ActionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ActionService:
    """ROS2 Action gRPC 서비스 정의
    """

    @staticmethod
    def SendGoal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wrosbridge.v1.ActionService/SendGoal',
            wrosbridge_dot_v1_dot_action__pb2.SendGoalRequest.SerializeToString,
            wrosbridge_dot_v1_dot_action__pb2.SendGoalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelGoal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wrosbridge.v1.ActionService/CancelGoal',
            wrosbridge_dot_v1_dot_action__pb2.CancelGoalRequest.SerializeToString,
            wrosbridge_dot_v1_dot_action__pb2.CancelGoalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wrosbridge.v1.ActionService/GetResult',
            wrosbridge_dot_v1_dot_action__pb2.GetResultRequest.SerializeToString,
            wrosbridge_dot_v1_dot_action__pb2.GetResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/wrosbridge.v1.ActionService/StreamFeedback',
            wrosbridge_dot_v1_dot_action__pb2.FeedbackStreamRequest.SerializeToString,
            wrosbridge_dot_v1_dot_action__pb2.FeedbackStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
