# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from remote_ros_mcp.proto.wrosbridge.v1 import admin_pb2 as wrosbridge_dot_v1_dot_admin__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in wrosbridge/v1/admin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdminServiceStub:
    """-------------------------------------------------------------
    4. AdminService gRPC 서비스 정의
    -------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetParameters = channel.unary_unary(
                '/wrosbridge.v1.AdminService/GetParameters',
                request_serializer=wrosbridge_dot_v1_dot_admin__pb2.GetParametersRequest.SerializeToString,
                response_deserializer=wrosbridge_dot_v1_dot_admin__pb2.GetParametersResponse.FromString,
                _registered_method=True)
        self.SetParameters = channel.unary_unary(
                '/wrosbridge.v1.AdminService/SetParameters',
                request_serializer=wrosbridge_dot_v1_dot_admin__pb2.SetParametersRequest.SerializeToString,
                response_deserializer=wrosbridge_dot_v1_dot_admin__pb2.SetParametersResponse.FromString,
                _registered_method=True)
        self.StreamParameterEvents = channel.unary_stream(
                '/wrosbridge.v1.AdminService/StreamParameterEvents',
                request_serializer=wrosbridge_dot_v1_dot_admin__pb2.StreamParameterEventsRequest.SerializeToString,
                response_deserializer=wrosbridge_dot_v1_dot_admin__pb2.ParameterEvent.FromString,
                _registered_method=True)
        self.LookupTF = channel.unary_unary(
                '/wrosbridge.v1.AdminService/LookupTF',
                request_serializer=wrosbridge_dot_v1_dot_admin__pb2.LookupTFRequest.SerializeToString,
                response_deserializer=wrosbridge_dot_v1_dot_admin__pb2.LookupTFResponse.FromString,
                _registered_method=True)
        self.StreamTF = channel.unary_stream(
                '/wrosbridge.v1.AdminService/StreamTF',
                request_serializer=wrosbridge_dot_v1_dot_admin__pb2.StreamTFRequest.SerializeToString,
                response_deserializer=wrosbridge_dot_v1_dot_admin__pb2.TFTransform.FromString,
                _registered_method=True)
        self.GetGraph = channel.unary_unary(
                '/wrosbridge.v1.AdminService/GetGraph',
                request_serializer=wrosbridge_dot_v1_dot_admin__pb2.GetGraphRequest.SerializeToString,
                response_deserializer=wrosbridge_dot_v1_dot_admin__pb2.GetGraphResponse.FromString,
                _registered_method=True)
        self.StreamGraphChanges = channel.unary_stream(
                '/wrosbridge.v1.AdminService/StreamGraphChanges',
                request_serializer=wrosbridge_dot_v1_dot_admin__pb2.StreamGraphChangesRequest.SerializeToString,
                response_deserializer=wrosbridge_dot_v1_dot_admin__pb2.GraphChangeEvent.FromString,
                _registered_method=True)


class AdminServiceServicer:
    """-------------------------------------------------------------
    4. AdminService gRPC 서비스 정의
    -------------------------------------------------------------

    """

    def GetParameters(self, request, context):
        """Parameter APIs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamParameterEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookupTF(self, request, context):
        """TF APIs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTF(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGraph(self, request, context):
        """Graph APIs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamGraphChanges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParameters,
                    request_deserializer=wrosbridge_dot_v1_dot_admin__pb2.GetParametersRequest.FromString,
                    response_serializer=wrosbridge_dot_v1_dot_admin__pb2.GetParametersResponse.SerializeToString,
            ),
            'SetParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.SetParameters,
                    request_deserializer=wrosbridge_dot_v1_dot_admin__pb2.SetParametersRequest.FromString,
                    response_serializer=wrosbridge_dot_v1_dot_admin__pb2.SetParametersResponse.SerializeToString,
            ),
            'StreamParameterEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamParameterEvents,
                    request_deserializer=wrosbridge_dot_v1_dot_admin__pb2.StreamParameterEventsRequest.FromString,
                    response_serializer=wrosbridge_dot_v1_dot_admin__pb2.ParameterEvent.SerializeToString,
            ),
            'LookupTF': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupTF,
                    request_deserializer=wrosbridge_dot_v1_dot_admin__pb2.LookupTFRequest.FromString,
                    response_serializer=wrosbridge_dot_v1_dot_admin__pb2.LookupTFResponse.SerializeToString,
            ),
            'StreamTF': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTF,
                    request_deserializer=wrosbridge_dot_v1_dot_admin__pb2.StreamTFRequest.FromString,
                    response_serializer=wrosbridge_dot_v1_dot_admin__pb2.TFTransform.SerializeToString,
            ),
            'GetGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGraph,
                    request_deserializer=wrosbridge_dot_v1_dot_admin__pb2.GetGraphRequest.FromString,
                    response_serializer=wrosbridge_dot_v1_dot_admin__pb2.GetGraphResponse.SerializeToString,
            ),
            'StreamGraphChanges': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamGraphChanges,
                    request_deserializer=wrosbridge_dot_v1_dot_admin__pb2.StreamGraphChangesRequest.FromString,
                    response_serializer=wrosbridge_dot_v1_dot_admin__pb2.GraphChangeEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wrosbridge.v1.AdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wrosbridge.v1.AdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminService:
    """-------------------------------------------------------------
    4. AdminService gRPC 서비스 정의
    -------------------------------------------------------------

    """

    @staticmethod
    def GetParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wrosbridge.v1.AdminService/GetParameters',
            wrosbridge_dot_v1_dot_admin__pb2.GetParametersRequest.SerializeToString,
            wrosbridge_dot_v1_dot_admin__pb2.GetParametersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wrosbridge.v1.AdminService/SetParameters',
            wrosbridge_dot_v1_dot_admin__pb2.SetParametersRequest.SerializeToString,
            wrosbridge_dot_v1_dot_admin__pb2.SetParametersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamParameterEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/wrosbridge.v1.AdminService/StreamParameterEvents',
            wrosbridge_dot_v1_dot_admin__pb2.StreamParameterEventsRequest.SerializeToString,
            wrosbridge_dot_v1_dot_admin__pb2.ParameterEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LookupTF(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wrosbridge.v1.AdminService/LookupTF',
            wrosbridge_dot_v1_dot_admin__pb2.LookupTFRequest.SerializeToString,
            wrosbridge_dot_v1_dot_admin__pb2.LookupTFResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTF(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/wrosbridge.v1.AdminService/StreamTF',
            wrosbridge_dot_v1_dot_admin__pb2.StreamTFRequest.SerializeToString,
            wrosbridge_dot_v1_dot_admin__pb2.TFTransform.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wrosbridge.v1.AdminService/GetGraph',
            wrosbridge_dot_v1_dot_admin__pb2.GetGraphRequest.SerializeToString,
            wrosbridge_dot_v1_dot_admin__pb2.GetGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamGraphChanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/wrosbridge.v1.AdminService/StreamGraphChanges',
            wrosbridge_dot_v1_dot_admin__pb2.StreamGraphChangesRequest.SerializeToString,
            wrosbridge_dot_v1_dot_admin__pb2.GraphChangeEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
