# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wrosbridge/v1/common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'wrosbridge/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1awrosbridge/v1/common.proto\x12\rwrosbridge.v1\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\"C\n\x06Header\x12\'\n\x05stamp\x18\x01 \x01(\x0b\x32\x18.wrosbridge.v1.Timestamp\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"8\n\nQuaternion\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\x42\x1cZ\x1awrosbridge/v1;wrosbridgev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wrosbridge.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032wrosbridge/v1;wrosbridgev1'
  _globals['_TIMESTAMP']._serialized_start=45
  _globals['_TIMESTAMP']._serialized_end=88
  _globals['_HEADER']._serialized_start=90
  _globals['_HEADER']._serialized_end=157
  _globals['_VECTOR3']._serialized_start=159
  _globals['_VECTOR3']._serialized_end=201
  _globals['_QUATERNION']._serialized_start=203
  _globals['_QUATERNION']._serialized_end=259
# @@protoc_insertion_point(module_scope)
