# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wrosbridge/v1/health.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'wrosbridge/v1/health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1awrosbridge/v1/health.proto\x12\rwrosbridge.v1\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\x93\x01\n\x13HealthCheckResponse\x12@\n\x06status\x18\x01 \x01(\x0e\x32\x30.wrosbridge.v1.HealthCheckResponse.ServingStatus\":\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x32X\n\x06Health\x12N\n\x05\x43heck\x12!.wrosbridge.v1.HealthCheckRequest\x1a\".wrosbridge.v1.HealthCheckResponseB\x1cZ\x1awrosbridge/v1;wrosbridgev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wrosbridge.v1.health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032wrosbridge/v1;wrosbridgev1'
  _globals['_HEALTHCHECKREQUEST']._serialized_start=45
  _globals['_HEALTHCHECKREQUEST']._serialized_end=82
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=85
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=232
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=174
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=232
  _globals['_HEALTH']._serialized_start=234
  _globals['_HEALTH']._serialized_end=322
# @@protoc_insertion_point(module_scope)
