# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from remote_ros_mcp.proto.wrosbridge.v1 import service_pb2 as wrosbridge_dot_v1_dot_service__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in wrosbridge/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServiceServiceStub:
    """SRV-001: ROS2 서비스 호출을 위한 gRPC 서비스 인터페이스.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallService = channel.unary_unary(
                '/wrosbridge.v1.ServiceService/CallService',
                request_serializer=wrosbridge_dot_v1_dot_service__pb2.ServiceRequest.SerializeToString,
                response_deserializer=wrosbridge_dot_v1_dot_service__pb2.ServiceResponse.FromString,
                _registered_method=True)


class ServiceServiceServicer:
    """SRV-001: ROS2 서비스 호출을 위한 gRPC 서비스 인터페이스.
    """

    def CallService(self, request, context):
        """Unary gRPC 호출을 ROS2 Service Client로 디스패치하고 결과를 반환합니다.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallService': grpc.unary_unary_rpc_method_handler(
                    servicer.CallService,
                    request_deserializer=wrosbridge_dot_v1_dot_service__pb2.ServiceRequest.FromString,
                    response_serializer=wrosbridge_dot_v1_dot_service__pb2.ServiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wrosbridge.v1.ServiceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wrosbridge.v1.ServiceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServiceService:
    """SRV-001: ROS2 서비스 호출을 위한 gRPC 서비스 인터페이스.
    """

    @staticmethod
    def CallService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wrosbridge.v1.ServiceService/CallService',
            wrosbridge_dot_v1_dot_service__pb2.ServiceRequest.SerializeToString,
            wrosbridge_dot_v1_dot_service__pb2.ServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
