# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wrosbridge/v1/service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'wrosbridge/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from remote_ros_mcp.proto.wrosbridge.v1 import common_pb2 as wrosbridge_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bwrosbridge/v1/service.proto\x12\rwrosbridge.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1awrosbridge/v1/common.proto\"\xb4\x01\n\x0eServiceRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12/\n\x07timeout\x18\x04 \x01(\x0b\x32\x19.google.protobuf.DurationH\x00\x88\x01\x01\x12*\n\x06header\x18\x05 \x01(\x0b\x32\x15.wrosbridge.v1.HeaderH\x01\x88\x01\x01\x42\n\n\x08_timeoutB\t\n\x07_header\"\xa0\x01\n\x0fServiceResponse\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\x0f\n\x07success\x18\x04 \x01(\x08\x12\x15\n\rerror_message\x18\x05 \x01(\t\x12*\n\x06header\x18\x06 \x01(\x0b\x32\x15.wrosbridge.v1.HeaderH\x00\x88\x01\x01\x42\t\n\x07_header2^\n\x0eServiceService\x12L\n\x0b\x43\x61llService\x12\x1d.wrosbridge.v1.ServiceRequest\x1a\x1e.wrosbridge.v1.ServiceResponseB\x1cZ\x1awrosbridge/v1;wrosbridgev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wrosbridge.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032wrosbridge/v1;wrosbridgev1'
  _globals['_SERVICEREQUEST']._serialized_start=107
  _globals['_SERVICEREQUEST']._serialized_end=287
  _globals['_SERVICERESPONSE']._serialized_start=290
  _globals['_SERVICERESPONSE']._serialized_end=450
  _globals['_SERVICESERVICE']._serialized_start=452
  _globals['_SERVICESERVICE']._serialized_end=546
# @@protoc_insertion_point(module_scope)
