# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from remote_ros_mcp.proto.wrosbridge.v1 import topic_pb2 as wrosbridge_dot_v1_dot_topic__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in wrosbridge/v1/topic_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TopicServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_stream(
                '/wrosbridge.v1.TopicService/Subscribe',
                request_serializer=wrosbridge_dot_v1_dot_topic__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=wrosbridge_dot_v1_dot_topic__pb2.TopicMessage.FromString,
                _registered_method=True)
        self.Publish = channel.unary_unary(
                '/wrosbridge.v1.TopicService/Publish',
                request_serializer=wrosbridge_dot_v1_dot_topic__pb2.PublishRequest.SerializeToString,
                response_deserializer=wrosbridge_dot_v1_dot_topic__pb2.PublishResponse.FromString,
                _registered_method=True)


class TopicServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Subscribe(self, request, context):
        """토픽을 구독하고 메시지 스트림을 받는다.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Publish(self, request, context):
        """토픽에 메시지를 발행한다.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TopicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=wrosbridge_dot_v1_dot_topic__pb2.SubscribeRequest.FromString,
                    response_serializer=wrosbridge_dot_v1_dot_topic__pb2.TopicMessage.SerializeToString,
            ),
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=wrosbridge_dot_v1_dot_topic__pb2.PublishRequest.FromString,
                    response_serializer=wrosbridge_dot_v1_dot_topic__pb2.PublishResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wrosbridge.v1.TopicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wrosbridge.v1.TopicService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TopicService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/wrosbridge.v1.TopicService/Subscribe',
            wrosbridge_dot_v1_dot_topic__pb2.SubscribeRequest.SerializeToString,
            wrosbridge_dot_v1_dot_topic__pb2.TopicMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wrosbridge.v1.TopicService/Publish',
            wrosbridge_dot_v1_dot_topic__pb2.PublishRequest.SerializeToString,
            wrosbridge_dot_v1_dot_topic__pb2.PublishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
