# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wrosbridge/v1/topic.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'wrosbridge/v1/topic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from remote_ros_mcp.proto.wrosbridge.v1 import common_pb2 as wrosbridge_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19wrosbridge/v1/topic.proto\x12\rwrosbridge.v1\x1a\x1awrosbridge/v1/common.proto\"u\n\x0cTopicMessage\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\x10\n\x08sequence\x18\x04 \x01(\x04\x12%\n\x06header\x18\x05 \x01(\x0b\x32\x15.wrosbridge.v1.Header\"/\n\x10SubscribeRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\">\n\x0ePublishRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\"#\n\x0fPublishResponse\x12\x10\n\x08sequence\x18\x01 \x01(\x04\x32\xa5\x01\n\x0cTopicService\x12K\n\tSubscribe\x12\x1f.wrosbridge.v1.SubscribeRequest\x1a\x1b.wrosbridge.v1.TopicMessage0\x01\x12H\n\x07Publish\x12\x1d.wrosbridge.v1.PublishRequest\x1a\x1e.wrosbridge.v1.PublishResponseB\x1cZ\x1awrosbridge/v1;wrosbridgev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wrosbridge.v1.topic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032wrosbridge/v1;wrosbridgev1'
  _globals['_TOPICMESSAGE']._serialized_start=72
  _globals['_TOPICMESSAGE']._serialized_end=189
  _globals['_SUBSCRIBEREQUEST']._serialized_start=191
  _globals['_SUBSCRIBEREQUEST']._serialized_end=238
  _globals['_PUBLISHREQUEST']._serialized_start=240
  _globals['_PUBLISHREQUEST']._serialized_end=302
  _globals['_PUBLISHRESPONSE']._serialized_start=304
  _globals['_PUBLISHRESPONSE']._serialized_end=339
  _globals['_TOPICSERVICE']._serialized_start=342
  _globals['_TOPICSERVICE']._serialized_end=507
# @@protoc_insertion_point(module_scope)
